### ISSUE TITLE
Reveal moves page behind it

### ISSUE THREAD

**Issue by drexxdk** [foundation/foundation-sites#11293]
## What should happen?
1. you click on a reveal button
2. body gets overflow-y: scroll that are disabled (or just the space the scrollbar takes) and the reveal opens on top of the page, where its scrollbar is on top of body scrollbar

## What happens instead?
1. you click on a reveal button
2. body gets overflow-y: hidden that causes the page content to move (since the scrollbar was taking arround 16px) and then the reveal opens on top of it. 

## Possible Solution

In your foundation.js, you should add a trigger for before reveal opens and before reveal closes.
I added this: this.$element.trigger('beforeopen.zf.reveal'); 

In my JS I added the following:

```js
var scrollTop = 0;

$(window).on("beforeopen.zf.reveal .o-nextmodal", function () {
    // before modal opens
    // base-wrapper is first child of body
    scrollTop = Math.max($('html').scrollTop(), $('body').scrollTop(), $('#base-wrapper').scrollTop());
});
$(window).on("open.zf.reveal .o-nextmodal", function () {
    // after modal opens
    $('body').addClass('is-reveal-open'); // it doesn't have this on at this state for some reason?
    $('#base-wrapper').scrollTop(scrollTop);
});
$(window).on("closed.zf.reveal .o-nextmodal", function () {
    // after modal closes
    $('html, body').scrollTop(scrollTop);
});
```

In my SCSS i added the following: 

```scss
body.is-reveal-open {
   overflow: unset !important;

   #base-wrapper { // first child of body
       overflow-y: scroll;
   }
}
```

## Test Case and/or Steps to Reproduce

How to reproduce:

1. Go to https://foundation.zurb.com/sites/docs/reveal.html
2. Click on the button "Click me for a modal"
3. You can now see that everything behind the revael moves to the right

## Your Environment

- Foundation version(s) used: version: 6.3.1
- Browser(s) name and version(s): Google Chrome 66.0.3359.181 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10 desktop

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
> You can now see that everything behind the revael moves to the right

This is intended when a scrollbar is removed and normal so far.

**Comment by DanielRuf** [comment]
I can not reproduce it anymore.

**Comment by guyvanbael** [comment]
This is still an issue. The fix @drexxdk suggests solves the issue though :-)

**Comment by DanielRuf** [comment]
> This is still an issue. The fix @drexxdk suggests solves the issue though :-)

I could not reproduce it on current Chrome and Firefox versions. Please provide more info so we can reproduce it.

**Comment by DanielRuf** [comment]
>     * Foundation version(s) used: version: 6.3.1

This is outdated. We have fixed this in the latest releases. Please update foundation-sites to the latest version.

**Comment by guyvanbael** [comment]
@DanielRuf I'm using foundation cli to spin up projects (using zurb stack) ... weird that it seems like it's pulling in 6.5.1 instead of 6.5.3 (which seems to be the latest...)

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-cli/blob/master/lib/commands/new.js does a `git clone` of the ZURB template.

https://github.com/foundation/foundation-zurb-template/blob/master/package.json#L13

Which is also in the lockfiles.
See https://github.com/foundation/foundation-zurb-template/blob/master/package-lock.json#L4877

So you have to run `npm update foundation-sites` to get the latest release.

**Comment by guyvanbael** [comment]
@DanielRuf just update foundation sites to 6.5.3, but issue still remains... so i added @drexxdk fix back in. I've tested on chrome, firefox, safari (osx 10.14.1)

**Comment by DanielRuf** [comment]
> @DanielRuf just update foundation sites to 6.5.3, but issue still remains... so i added @drexxdk fix back in. I've tested on chrome, firefox, safari (osx 10.14.1)

Please test it on our documentation page. Also as I have already wrote, please open a new issue and provide all required information so we can reproduce it.

**Comment by kevinmu17** [comment]
Check if you have this in your CSS:
`html,body {
  height: 100%;
}`

It was a hell of a search, but somehow this breaks the whole reveal modal like above, background scrolling or disappearing completely.

**Comment by mischa-s** [comment]
> Check if you have this in your CSS:
> `html,body { height: 100%; }`
> 
> It was a hell of a search, but somehow this breaks the whole reveal modal like above, background scrolling or disappearing completely.

Thanks!! I've just run into this problem of the background disappearing completely - happening with `{height: 100vh}` but I suspect a similar bug - did you find a solution?
